### PR TITLE
A couple new features

### PR DESCRIPTION
**Pull request by ghost**
- Chairo compatibility
- Pass in session config

### CODE REVIEW

**Comment by ghost** [comment]
If everything looks good could the latest from this repo and hapi-to-express be published to npm?

**Comment by ghost** [comment]
Hi @jakepruitt :)  Would it be possible to get this published to npm?

**Comment by jakepruitt** [comment]
Hey, @wprl thanks for pinging me! What's your npm username? @wprl?

**Comment by jakepruitt** [comment]
Added you as a collaborator and npm owner :)

**Comment by ghost** [comment]
Thanks :)

**Comment by ghost** [comment]
Would it also be possible to also get npm publish permission on hapi-to-express?

**Comment by jakepruitt** [comment]
Sure @wprl! I also added a test in master branch that just describes the basic case in the README. Seems to be getting a 500 error and showing some `deprecated` warnings for the cookie package. If you have time, could you look into those? I think I'm going to sit down with these hapi projects this weekend and get tests and major improvements done.

**Comment by ghost** [comment]
OK cool.  I will look into those.

**Pull request merged**
